### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by NathanUrwin** [NathanUrwin/cookie-cookie#6]

**Comment by SKalt** [comment]
+1 for this one. I encountered trouble at the first use of [urllib2, which python3 lacks](https://docs.python.org/2/library/urllib2.html#module-urllib2).

**Comment by tuxredux** [comment]
Hey @SKalt :wave: 

I appreciate your feedback! Indeed, it seems the issue has already been duplicated (#8). I'm currently learning [test-driven development](https://www.obeythetestinggoat.com/). Once I've got testing under my belt, I plan on revisiting and revamping all my open-source projects. Hopefully, this will be very soon! :slightly_smiling_face: 

Thanks for your interest in cookie-cookie!

**Comment by SKalt** [comment]
When you do, I'd recommend looking into the [2to3]( https://docs.python.org/3/library/2to3.html) python translator.
